name: uidesign1to100
description: "A new Flutter project."

publish_to: 'none'


version: 1.0.0+1

environment:
  sdk: ^3.7.2

dependencies:
  flutter:
    sdk: flutter


  cupertino_icons: ^1.0.8
  responsive_sizer: ^3.3.1
  gap: 
  animate_do: ^4.2.0
  flutter_staggered_grid_view: ^0.7.0
  flutter_staggered_animations: ^1.1.1
  glassmorphism: ^3.0.0
  google_fonts: ^6.2.1

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^5.0.0


flutter:


  uses-material-design: true

  # assets:
  #   - images/a_dot_burr.jpeg
  #   - images/a_dot_ham.jpeg


